name: first-challenge

on: [push]

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
    - run: date

  job2:
    runs-on: windows-latest
    steps:
    - run: date

  job3:
    runs-on: macOS-latest
    steps:
      - run: date

  job4:
    runs-on: ubuntu-latest
    needs: [job1, job2, job3]
    steps:
      - run: date
  
